<?php

declare(strict_types=1);

require_once(implode(separator: DIRECTORY_SEPARATOR, array: [$_SERVER['DOCUMENT_ROOT'], 'requires.php']));

$api = new Supergnaw\PlayFabPhp\PlayFab(PLAYFAB_APP_ID);

$statsListing = [
    "Refining1N",
    "Refining1O",
    "Refining1P",
    "Refining2N",
    "Refining2O",
    "Refining2P",
    "Refining2Q",
    "Refining3N",
    "Refining3O",
    "Refining3P",
    "Refining3Q",
    "refining1O",
    "refining1P",
    "refining2O",
    "refining2P",
    "refining2Q",
    "refining3O",
    "refining3P",
    "refining3Q",
    "Refining4N",
    "refining4O",
    "refining4P",
    "refining4Q",
    "Refining5N",
    "refining5O",
    "refining5P",
    "refining5Q",
    "Refining4V",
    "Refining4W",
    "Refining4X",
    "Refining4Y",
    "Refining5V",
    "Refining5W",
    "Refining5X",
    "Refining5Y",
    "MissionsDoneGenerated",
    "Scanned",
    "ScannedGenerated",
    "ScannedBelt",
    "ShipsDestroyed",
    "ShipsDestroyedP1",
    "ShipsDestroyedProgenitor",
    "ShipsDestroyedTanoch",
    "ShipsDestroyedYaot",
    "ShipsDestroyedAmassari",
    "ShipsDestroyedHiigaran",
    "ShipsDestroyedP1T1",
    "ShipsDestroyedP1T2",
    "ShipsDestroyedP1T3",
    "ShipsDestroyedP1T4",
    "ShipsDestroyedP1T5",
    "ShipsDestroyedProgenitorT1",
    "ShipsDestroyedProgenitorT2",
    "ShipsDestroyedProgenitorT3",
    "ShipsDestroyedProgenitorT4",
    "ShipsDestroyedProgenitorT5",
    "ShipsDestroyedYaotT1",
    "ShipsDestroyedYaotT2",
    "ShipsDestroyedYaotT3",
    "ShipsDestroyedYaotT4",
    "ShipsDestroyedYaotT5",
    "ShipsDestroyedTanochT1",
    "ShipsDestroyedTanochT2",
    "ShipsDestroyedTanochT3",
    "ShipsDestroyedTanochT4",
    "ShipsDestroyedTanochT5",
    "ShipsDestroyedAmassariT1",
    "ShipsDestroyedAmassariT2",
    "ShipsDestroyedAmassariT3",
    "ShipsDestroyedAmassariT4",
    "ShipsDestroyedAmassariT5",
    "ShipsDestroyedT1",
    "ShipsDestroyedT2",
    "ShipsDestroyedT3",
    "ShipsDestroyedT4",
    "ShipsDestroyedT5",
    "Mined",
    "Mined0A",
    "Mined1A",
    "Mined1B",
    "Mined1C",
    "Mined2A",
    "Mined2B",
    "Mined2C",
    "Mined2D",
    "Mined3A",
    "Mined3B",
    "Mined3C",
    "Mined3D",
    "Mined3E",
    "Mined3F",
    "Mined3G",
    "Mined3H",
    "Mined4E",
    "Mined4F",
    "Mined4G",
    "Mined4H",
    "Mined5E",
    "Mined5F",
    "Mined5G",
    "Mined5H",
    "Mined4A",
    "Mined4B",
    "Mined4C",
    "Mined4D",
    "Mined5A",
    "Mined5B",
    "Mined5C",
    "Mined5D",
    "IdleMined",
    "RepTr1",
    "RepTanoch",
    "RepYaot",
    "RepAmassari",
    "playerxp"
];
$confirmedStats = [
    "Refining1N", "Refining1O", "Refining1P", "Refining2N", "Refining2O", "Refining2P", "Refining2Q", "Refining3N",
    "Refining3O", "Refining3P", "Refining3Q", "Refining4N", "MissionsDoneGenerated", "Scanned",  "ScannedGenerated",
    "ScannedBelt", "ShipsDestroyed", "ShipsDestroyedP1", "ShipsDestroyedProgenitor", "ShipsDestroyedTanoch",
    "ShipsDestroyedYaot", "ShipsDestroyedAmassari", "ShipsDestroyedHiigaran", "ShipsDestroyedP1T1",
    "ShipsDestroyedP1T2", "ShipsDestroyedP1T3", "ShipsDestroyedProgenitorT1", "ShipsDestroyedProgenitorT2",
    "ShipsDestroyedProgenitorT3", "ShipsDestroyedProgenitorT4", "ShipsDestroyedYaotT1", "ShipsDestroyedYaotT2",
    "ShipsDestroyedYaotT3", "ShipsDestroyedTanochT2", "ShipsDestroyedTanochT3", "ShipsDestroyedAmassariT4",
    "ShipsDestroyedT1", "ShipsDestroyedT2", "ShipsDestroyedT3", "ShipsDestroyedT4", "Mined", "Mined0A", "Mined1A",
    "Mined1B", "Mined1C", "Mined2A", "Mined2B", "Mined2C", "Mined2D", "Mined3A", "Mined3B", "Mined3C", "Mined3D",
    "Mined3E", "Mined3F", "Mined3G", "Mined3H", "Mined4E", "Mined4F", "Mined4G", "Mined4H", "Mined4A", "Mined4B",
    "Mined4C", "Mined4D", "IdleMined", "RepTr1", "RepTanoch", "RepYaot", "RepAmassari", "Scanned", "ScannedBelt",
    "ScannedGenerated", "Upgrade", "UpgradeExternal", "UpgradeInternal"
];
//exit();

/* Show Leaderboards */
$statisticsWhitelist = [
    "RepTr1",
    "RepYaot",
    "RepTanoch",
    "RepVaygr",
    "RepAma",
    "RepClan",
    "Scanned",
    "ScannedBelt",
    "ScannedGenerated",
    "Upgrade",
    "UpgradeExternal",
    "UpgradeInternal"
];

$other = [
    "IdleMined"
];

$validStats = [];
$stats = [
    "RepTr1RepTr1", "RepYaot", "RepTanoch", "RepVaygr", "ShipsDestroyed", "RepAmassari", "RepClan", "Scanned",
    "ScannedGenerated", "MissionsDone", "MissionsDoneGenerated", "MissionsDoneFaction", "MissionsDoneTr1",
    "MissionsDoneYaot", "MissionsDoneTanoch", "MissionsDoneVaygr", "MissionsDoneMain", "MissionsDoneStrike", "Mined",
    "Mined1A", "Mined1B", "Mined1C", "Mined2A", "Mined2B", "Mined2C", "Mined2D", "Mined3A", "Mined3B", "Mined3C",
    "Mined3D", "Mined4A", "Mined4B", "Mined4C", "Mined4D", "Mined5A", "Mined5B", "Mined5C", "Mined5D", "Refining1N",
    "Refining1O", "Refining1P", "Refining2N", "Refining2O", "Refining2P", "Refining2Q", "Refining3N", "Refining3O",
    "Refining3P", "Refining3Q", "Refining4N", "Refining4O", "Refining4P", "Refining4Q", "Refining5N", "Refining5O",
    "Refining5P", "Refining5Q", "CraftingStrikeCraft", "CraftingExternal", "CraftingInternal", "UpgradeExternal",
    "UpgradeInternal", "IncomeSell", "Mined0A", "ScannedSystem", "IdleMined", "IdleMined1A", "IdleMined1B",
    "IdleMined1C", "IdleMined2A", "IdleMined2B", "IdleMined2C", "IdleMined2D", "IdleMined3A", "IdleMined3B",
    "IdleMined3C", "IdleMined3D", "IdleMined4A", "IdleMined4B", "IdleMined4C", "IdleMined4D", "IdleMined5A",
    "IdleMined5B", "IdleMined5C", "IdleMined5D", "IdleMined0A", "Mined3E", "Mined3F", "Mined3G", "Mined3H", "Mined4E",
    "Mined4F", "Mined4G", "Mined4H", "Mined5E", "Mined5F", "Mined5G", "Mined5H", "Mined4R", "Mined4S", "Mined4T",
    "Mined4U", "Mined4V", "Mined4W", "Mined4X", "Mined4Y", "Mined5R", "Mined5S", "Mined5T", "Mined5U", "Mined5V",
    "Mined5W", "Mined5X", "Mined5Y", "ShipsDestroyedP1", "ShipsDestroyedYaot", "ShipsDestroyedTanoch",
    "ShipsDestroyedProgenitor", "ShipsDestroyedP2", "ShipsDestroyedVaygr", "ShipsDestroyedHiigaran",
    "ShipsDestroyedDarkHiigaran", "ShipsDestroyedAmassari", "ShipsDestroyedP1T1", "ShipsDestroyedP1T2",
    "ShipsDestroyedP1T3", "ShipsDestroyedP1T4", "ShipsDestroyedP1T5", "ShipsDestroyedYaotT1", "ShipsDestroyedYaotT2",
    "ShipsDestroyedYaotT3", "ShipsDestroyedYaotT4", "ShipsDestroyedYaotT5", "ShipsDestroyedTanochT1",
    "ShipsDestroyedTanochT2", "ShipsDestroyedTanochT3", "ShipsDestroyedTanochT4", "ShipsDestroyedTanochT5",
    "ShipsDestroyedProgenitorT1", "ShipsDestroyedProgenitorT2", "ShipsDestroyedProgenitorT3",
    "ShipsDestroyedProgenitorT4", "ShipsDestroyedProgenitorT5", "ShipsDestroyedP2T1", "ShipsDestroyedP2T2",
    "ShipsDestroyedP2T3", "ShipsDestroyedP2T4", "ShipsDestroyedP2T5", "ShipsDestroyedVaygrT1", "ShipsDestroyedVaygrT2",
    "ShipsDestroyedVaygrT3", "ShipsDestroyedVaygrT4", "ShipsDestroyedVaygrT5", "ShipsDestroyedHiigaranT1",
    "ShipsDestroyedHiigaranT2", "ShipsDestroyedHiigaranT3", "ShipsDestroyedHiigaranT4", "ShipsDestroyedHiigaranT5",
    "ShipsDestroyedP1T0", "ShipsDestroyedYaotT0", "ShipsDestroyedTanochT0", "ShipsDestroyedProgenitorT0",
    "ShipsDestroyedP2T0", "ShipsDestroyedVaygrT0", "ShipsDestroyedHiigaranT0", "ShipsDestroyedT1", "ShipsDestroyedT2",
    "ShipsDestroyedT3", "ShipsDestroyedT4", "ShipsDestroyedT5", "ShipsDestroyedT0", "ShipsDestroyedDarkHiigaranT4",
    "ShipsDestroyedDarkHiigaranT5", "ShipsDestroyedAmassariT4", "ShipsDestroyedAmassariT5", "QuestsDone",
    "QuestsDoneT1", "QuestsDoneT2", "QuestsDoneT3", "QuestsDoneT4", "QuestsDoneT5", "QuestsDoneT0", "QuestsDoneMain",
    "QuestsDoneDaily", "QuestsDoneWeekly", "QuestsDoneStrike", "QuestsDoneEvent", "QuestsDoneFaction",
    "QuestsDoneAchivement", "QuestsDoneHiigaran", "QuestsDoneYaot", "QuestsDoneTanoch", "QuestsDoneTr1",
    "QuestsDoneAmassari", "RefiningDroppedREE", "DroppedReeAA", "DroppedReeAB", "DroppedReeBA", "DroppedReeBB",
    "DroppedReeBC", "DroppedReeCA", "DroppedReeCB", "DroppedReeCC", "DroppedReeCD", "DroppedReeDA", "DroppedReeDB",
    "DroppedReeDC", "DroppedReeDD", "DroppedReeEA", "DroppedReeEB", "DroppedReeEC", "DroppedReeED",
    "Refining1N", "Refining1O", "Refining1P", "Refining2N", "Refining2O", "Refining2P", "Refining2Q", "Refining3N",
    "Refining3O", "Refining3P", "Refining3Q", "Refining4N", "MissionsDoneGenerated", "Scanned",  "ScannedGenerated",
    "ScannedBelt", "ShipsDestroyed", "ShipsDestroyedP1", "ShipsDestroyedProgenitor", "ShipsDestroyedTanoch",
    "ShipsDestroyedYaot", "ShipsDestroyedAmassari", "ShipsDestroyedHiigaran", "ShipsDestroyedP1T1",
    "ShipsDestroyedP1T2", "ShipsDestroyedP1T3", "ShipsDestroyedProgenitorT1", "ShipsDestroyedProgenitorT2",
    "ShipsDestroyedProgenitorT3", "ShipsDestroyedProgenitorT4", "ShipsDestroyedYaotT1", "ShipsDestroyedYaotT2",
    "ShipsDestroyedYaotT3", "ShipsDestroyedTanochT2", "ShipsDestroyedTanochT3", "ShipsDestroyedAmassariT4",
    "ShipsDestroyedT1", "ShipsDestroyedT2", "ShipsDestroyedT3", "ShipsDestroyedT4", "Mined", "Mined0A", "Mined1A",
    "Mined1B", "Mined1C", "Mined2A", "Mined2B", "Mined2C", "Mined2D", "Mined3A", "Mined3B", "Mined3C", "Mined3D",
    "Mined3E", "Mined3F", "Mined3G", "Mined3H", "Mined4E", "Mined4F", "Mined4G", "Mined4H", "Mined4A", "Mined4B",
    "Mined4C", "Mined4D", "IdleMined", "RepTr1", "RepTanoch", "RepYaot", "RepAmassari", "Scanned", "ScannedBelt",
    "ScannedGenerated", "Upgrade", "UpgradeExternal"];
//foreach ($stats as $statName) {
//    $path = "stats_{$statName}.json";
//    $response = $api->get_full_leaderboard(statName:$statName);
//    $jsonString = $response; // $jsonString = json_encode($jsonData, JSON_PRETTY_PRINT);
//    $fp = fopen($path, 'w');
//    fwrite($fp, $jsonString);
//    fclose($fp);
//    $response = json_decode($api->get_leaderboard(statName:$statName, maxResults: 1, startPosition: 0));
//    if (0 < count($response->compendium->Leaderboard)) {
//        $validStats[] = $statName;
//    }
//}
//var_dump($validStats);
//echo json_encode($validStats);
//var_dump($api->call_count());

//$validStats = [
//    "RepYaot",
//    "RepTanoch",
//    "ShipsDestroyed",
//    "RepAmassari",
//    "Scanned",
//    "ScannedGenerated",
//    "MissionsDone",
//    "MissionsDoneGenerated",
//    "MissionsDoneFaction",
//    "MissionsDoneTr1",
//    "MissionsDoneYaot",
//    "MissionsDoneTanoch",
//    "MissionsDoneMain",
//    "MissionsDoneStrike",
//    "Mined",
//    "Mined1A",
//    "Mined1B",
//    "Mined1C",
//    "Mined2A",
//    "Mined2B",
//    "Mined2C",
//    "Mined2D",
//    "Mined3A",
//    "Mined3B",
//    "Mined3C",
//    "Mined3D",
//    "Mined4A",
//    "Mined4B",
//    "Mined4C",
//    "Mined4D",
//    "Refining1N",
//    "Refining1O",
//    "Refining1P",
//    "Refining2N",
//    "Refining2O",
//    "Refining2P",
//    "Refining2Q",
//    "Refining3N",
//    "Refining3O",
//    "Refining3P",
//    "Refining3Q",
//    "Refining4N",
//    "Refining4O",
//    "Refining4P",
//    "Refining4Q",
//    "CraftingStrikeCraft",
//    "CraftingExternal",
//    "UpgradeExternal",
//    "IncomeSell",
//    "Mined0A",
//    "ScannedSystem",
//    "IdleMined",
//    "IdleMined1A",
//    "IdleMined1B",
//    "IdleMined1C",
//    "IdleMined2A",
//    "IdleMined2B",
//    "IdleMined2C",
//    "IdleMined2D",
//    "IdleMined3A",
//    "IdleMined3B",
//    "IdleMined3C",
//    "IdleMined3D",
//    "IdleMined4A",
//    "IdleMined4B",
//    "IdleMined4C",
//    "IdleMined4D",
//    "Mined3E",
//    "Mined3F",
//    "Mined3G",
//    "Mined3H",
//    "Mined4E",
//    "Mined4F",
//    "Mined4G",
//    "Mined4H",
//    "ShipsDestroyedP1",
//    "ShipsDestroyedYaot",
//    "ShipsDestroyedTanoch",
//    "ShipsDestroyedProgenitor",
//    "ShipsDestroyedP2",
//    "ShipsDestroyedVaygr",
//    "ShipsDestroyedHiigaran",
//    "ShipsDestroyedAmassari",
//    "ShipsDestroyedP1T1",
//    "ShipsDestroyedP1T2",
//    "ShipsDestroyedP1T3",
//    "ShipsDestroyedYaotT1",
//    "ShipsDestroyedYaotT2",
//    "ShipsDestroyedYaotT3",
//    "ShipsDestroyedTanochT2",
//    "ShipsDestroyedTanochT3",
//    "ShipsDestroyedProgenitorT1",
//    "ShipsDestroyedProgenitorT2",
//    "ShipsDestroyedProgenitorT3",
//    "ShipsDestroyedProgenitorT4",
//    "ShipsDestroyedP2T1",
//    "ShipsDestroyedVaygrT3",
//    "ShipsDestroyedHiigaranT1",
//    "ShipsDestroyedHiigaranT2",
//    "ShipsDestroyedHiigaranT3",
//    "ShipsDestroyedHiigaranT4",
//    "ShipsDestroyedP1T0",
//    "ShipsDestroyedProgenitorT0",
//    "ShipsDestroyedT1",
//    "ShipsDestroyedT2",
//    "ShipsDestroyedT3",
//    "ShipsDestroyedT4",
//    "ShipsDestroyedT0",
//    "ShipsDestroyedAmassariT4",
//    "QuestsDone",
//    "QuestsDoneT1",
//    "QuestsDoneT2",
//    "QuestsDoneT3",
//    "QuestsDoneT4",
//    "QuestsDoneT0",
//    "QuestsDoneMain",
//    "QuestsDoneDaily",
//    "QuestsDoneWeekly",
//    "QuestsDoneStrike",
//    "QuestsDoneFaction",
//    "QuestsDoneYaot",
//    "QuestsDoneTanoch",
//    "QuestsDoneTr1",
//    "QuestsDoneAmassari",
//    "RefiningDroppedREE",
//    "DroppedReeAA",
//    "DroppedReeAB",
//    "DroppedReeBA",
//    "DroppedReeBB",
//    "DroppedReeBC",
//    "DroppedReeCA",
//    "DroppedReeCB",
//    "DroppedReeCC",
//    "DroppedReeCD",
//    "DroppedReeDA",
//    "DroppedReeDB",
//    "DroppedReeDC",
//    "DroppedReeDD",
//    "Refining1N",
//    "Refining1O",
//    "Refining1P",
//    "Refining2N",
//    "Refining2O",
//    "Refining2P",
//    "Refining2Q",
//    "Refining3N",
//    "Refining3O",
//    "Refining3P",
//    "Refining3Q",
//    "Refining4N",
//    "MissionsDoneGenerated",
//    "Scanned",
//    "ScannedGenerated",
//    "ScannedBelt",
//    "ShipsDestroyed",
//    "ShipsDestroyedP1",
//    "ShipsDestroyedProgenitor",
//    "ShipsDestroyedTanoch",
//    "ShipsDestroyedYaot",
//    "ShipsDestroyedAmassari",
//    "ShipsDestroyedHiigaran",
//    "ShipsDestroyedP1T1",
//    "ShipsDestroyedP1T2",
//    "ShipsDestroyedP1T3",
//    "ShipsDestroyedProgenitorT1",
//    "ShipsDestroyedProgenitorT2",
//    "ShipsDestroyedProgenitorT3",
//    "ShipsDestroyedProgenitorT4",
//    "ShipsDestroyedYaotT1",
//    "ShipsDestroyedYaotT2",
//    "ShipsDestroyedYaotT3",
//    "ShipsDestroyedTanochT2",
//    "ShipsDestroyedTanochT3",
//    "ShipsDestroyedAmassariT4",
//    "ShipsDestroyedT1",
//    "ShipsDestroyedT2",
//    "ShipsDestroyedT3",
//    "ShipsDestroyedT4",
//    "Mined",
//    "Mined0A",
//    "Mined1A",
//    "Mined1B",
//    "Mined1C",
//    "Mined2A",
//    "Mined2B",
//    "Mined2C",
//    "Mined2D",
//    "Mined3A",
//    "Mined3B",
//    "Mined3C",
//    "Mined3D",
//    "Mined3E",
//    "Mined3F",
//    "Mined3G",
//    "Mined3H",
//    "Mined4E",
//    "Mined4F",
//    "Mined4G",
//    "Mined4H",
//    "Mined4A",
//    "Mined4B",
//    "Mined4C",
//    "Mined4D",
//    "IdleMined",
//    "RepTr1",
//    "RepTanoch",
//    "RepYaot",
//    "RepAmassari",
//    "Scanned",
//    "ScannedBelt",
//    "ScannedGenerated",
//    "Upgrade",
//    "UpgradeExternal"
//];
//$validStats = [
//    "CraftingExternal",
//    "CraftingStrikeCraft",
//    "DroppedReeAA",
//    "DroppedReeAB",
//    "DroppedReeBA",
//    "DroppedReeBB",
//    "DroppedReeBC",
//    "DroppedReeCA",
//    "DroppedReeCB",
//    "DroppedReeCC",
//    "DroppedReeCD",
//    "DroppedReeDA",
//    "DroppedReeDB",
//    "DroppedReeDC",
//    "DroppedReeDD",
//    "IdleMined",
//    "IdleMined1A",
//    "IdleMined1B",
//    "IdleMined1C",
//    "IdleMined2A",
//    "IdleMined2B",
//    "IdleMined2C",
//    "IdleMined2D",
//    "IdleMined3A",
//    "IdleMined3B",
//    "IdleMined3C",
//    "IdleMined3D",
//    "IdleMined4A",
//    "IdleMined4B",
//    "IdleMined4C",
//    "IdleMined4D",
//    "IncomeSell",
//    "Mined",
//    "Mined0A",
//    "Mined1A",
//    "Mined1B",
//    "Mined1C",
//    "Mined2A",
//    "Mined2B",
//    "Mined2C",
//    "Mined2D",
//    "Mined3A",
//    "Mined3B",
//    "Mined3C",
//    "Mined3D",
//    "Mined3E",
//    "Mined3F",
//    "Mined3G",
//    "Mined3H",
//    "Mined4A",
//    "Mined4B",
//    "Mined4C",
//    "Mined4D",
//    "Mined4E",
//    "Mined4F",
//    "Mined4G",
//    "Mined4H",
//    "MissionsDone",
//    "MissionsDoneFaction",
//    "MissionsDoneGenerated",
//    "MissionsDoneMain",
//    "MissionsDoneStrike",
//    "MissionsDoneTanoch",
//    "MissionsDoneTr1",
//    "MissionsDoneYaot",
//    "QuestsDone",
//    "QuestsDoneAmassari",
//    "QuestsDoneDaily",
//    "QuestsDoneFaction",
//    "QuestsDoneMain",
//    "QuestsDoneStrike",
//    "QuestsDoneT0",
//    "QuestsDoneT1",
//    "QuestsDoneT2",
//    "QuestsDoneT3",
//    "QuestsDoneT4",
//    "QuestsDoneTanoch",
//    "QuestsDoneTr1",
//    "QuestsDoneWeekly",
//    "QuestsDoneYaot",
//    "Refining1N",
//    "Refining1O",
//    "Refining1P",
//    "Refining2N",
//    "Refining2O",
//    "Refining2P",
//    "Refining2Q",
//    "Refining3N",
//    "Refining3O",
//    "Refining3P",
//    "Refining3Q",
//    "Refining4N",
//    "Refining4O",
//    "Refining4P",
//    "Refining4Q",
//    "RefiningDroppedREE",
//    "RepAmassari",
//    "RepTanoch",
//    "RepTr1",
//    "RepYaot",
//    "Scanned",
//    "ScannedBelt",
//    "ScannedGenerated",
//    "ScannedSystem",
//    "ShipsDestroyed",
//    "ShipsDestroyedAmassari",
//    "ShipsDestroyedAmassariT4",
//    "ShipsDestroyedHiigaran",
//    "ShipsDestroyedHiigaranT1",
//    "ShipsDestroyedHiigaranT2",
//    "ShipsDestroyedHiigaranT3",
//    "ShipsDestroyedHiigaranT4",
//    "ShipsDestroyedP1",
//    "ShipsDestroyedP1T0",
//    "ShipsDestroyedP1T1",
//    "ShipsDestroyedP1T2",
//    "ShipsDestroyedP1T3",
//    "ShipsDestroyedP2",
//    "ShipsDestroyedP2T1",
//    "ShipsDestroyedProgenitor",
//    "ShipsDestroyedProgenitorT0",
//    "ShipsDestroyedProgenitorT1",
//    "ShipsDestroyedProgenitorT2",
//    "ShipsDestroyedProgenitorT3",
//    "ShipsDestroyedProgenitorT4",
//    "ShipsDestroyedT0",
//    "ShipsDestroyedT1",
//    "ShipsDestroyedT2",
//    "ShipsDestroyedT3",
//    "ShipsDestroyedT4",
//    "ShipsDestroyedTanoch",
//    "ShipsDestroyedTanochT2",
//    "ShipsDestroyedTanochT3",
//    "ShipsDestroyedVaygr",
//    "ShipsDestroyedVaygrT3",
//    "ShipsDestroyedYaot",
//    "ShipsDestroyedYaotT1",
//    "ShipsDestroyedYaotT2",
//    "ShipsDestroyedYaotT3",
//    "Upgrade",
//    "UpgradeExternal",
//];
//sort($validStats);
//$validStats = array_unique($validStats);
//echo json_encode($validStats);

$playerId = "ADA4E1380D35CDF2";
$characters = [
    "1019AFB4C4738999",
    "156A8D5C22D6EAAF",
    "221FA12AF8342040",
    "6DA819D4E896717A",
    "6F0F750FBB934F69",
    "7888E6EFDA20D847",
    "7F92866EB2949131",
    "85FA77FC1A9B2EBE",
    "C54D0290633DB2CF",
    "C6DA3BF368837DE1",
    "F46A568D530C8CA9",
    "FDC4833B7E11B1DC"
];



$characterId = $characters[7];

/* Show Character Stats */
//$api->get_characters(playFabId: $playerId);
//$api->print_response();

//$api->get_character_stats(characterId: $characterId);
//$api->print_response();

/* Show Player Stats */
$playerId = 'ADA4E1380D35CDF2';
//$response = $api->get_player_stats(playFabId: $playerId);
//$api->dump_response($response, true);

/* Show User Data */
//$response = $api->get_user_data($playerId);
//$api->dump_response($response, true);

/* Get News */
//$response = $api->get_news();
//$api->dump_response($response, true);

// Process Request URI
$uri = explode("/",trim($_SERVER['REQUEST_URI'],"/"));

/**
 * Generate Page Sections
 ***/

///// HTML Header /////
$header = generate_html_header();

///// Main Navigation Tabs /////
$navtabs = generate_navtabs();

/**
 * DISPLAY DATA
 */
echo "
<!DOCTYPE html>
<html>
    <head>
        {$header}
    </head>
    <body>
        {$navtabs}
        <div class='main hw-outer-box'>
            <div class='title'>HOMEWORLD MOBILE</div>
            <div class='subtitle'>Unofficial Guide</div> 
            <img src='/img/guidestone.jpg' style='width: 100%;max-width: 100%;'>
            <hr>
            <div class='hw-nav col1'>
                <a href='#top'><div>Top</div></a>
            </div>
            <hr>
            <p style='text-align: center'><a href='/console/'><img src='/img/25x25bdgB.GIF'></a></p>
        </div>
    </body>
</html>";
